sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
widgets:
   # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: profile
        # Author name
        author: trai25
        # Author title
        author_title: Designer
        # Author's current location
        # location: China
        # URL or path to the avatar image
        avatar: 
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://twitter.com/freemantis25'
        # Links to be shown on the bottom of the profile widget
        social_links:
            # Github:
                # icon: fab fa-github
                # url: 'https://github.com/ppoffice'
            # Facebook:
                # icon: fab fa-facebook
                # url: 'https://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/freemantis25'
            Dribbble:
                icon: fab fa-dribbble
                url: 'https://dribbble.com/trai25'
            RSS:
                icon: fas fa-rss
                url: 'https://feeds.feedburner.com/trai25'
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: toc
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: recent_posts
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: archives
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags
    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: links
        # Names and URLs of the sites
        links:
            Hexo: 'https://hexo.io'
            Icarus: 'https://github.com/ppoffice/hexo-theme-icarus'